name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, pcntl, bcmath, zip
        coverage: none

    - name: Copie .env.example vers .env
      run: cp .env.example .env

    - name: Composer install
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Generate key
      run: php artisan key:generate

    - name: Set permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Build Docker Image
      run: docker build -t formation-app .

    - name: Vérification simple Laravel (route:list)
      run: php artisan route:list
